FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache \
    ffmpeg \
    python3 \
    py3-pip \
    ca-certificates \
    fontconfig \
    ttf-dejavu \
    font-noto \
    font-noto-cjk \
    font-noto-emoji \
    font-noto-extra \
    font-noto-kannada
RUN fc-cache -fv
RUN pip3 install --break-system-packages edge-tts

#COPY . .
COPY package.json ./
COPY server ./server
COPY client ./client
COPY vite.config.ts ./
COPY shared ./shared
COPY db ./db
COPY drizzle.config.ts ./
COPY tsconfig.json ./
COPY types.d.ts ./
COPY main.py ./
COPY uv.lock ./
COPY entrypoint.sh ./
RUN mkdir -p public/uploads
RUN npm install --verbose
RUN echo "===== INSTALLED PACKAGES =====" && npm ls --depth=0

RUN echo "===== NODE_MODULES =====" && find node_modules -maxdepth 2 -type d

RUN npm run build


RUN chmod +x entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["./entrypoint.sh"]
#CMD ["node", "dist/index.js"]
#CMD ["npm", "start"]
