// Standardized district list for consistency across the application
export const INDIAN_DISTRICTS = [
  // Karnataka
  "Bagalkot", 
  "Ballari", 
  "Belagavi", 
  "Bengaluru Rural", 
  "Bengaluru Urban", 
  "Bidar", 
  "Chamarajanagar", 
  "Chikkaballapur", 
  "Chikkamagaluru", 
  "Chitradurga", 
  "Dakshina Kannada", 
  "Davanagere", 
  "Dharwad", 
  "Gadag", 
  "Hassan", 
  "Haveri", 
  "Kalaburagi", 
  "Kodagu", 
  "Kolar", 
  "Koppal", 
  "Mandya", 
  "Mysuru", 
  "Raichur", 
  "Ramanagara", 
  "Shivamogga", 
  "Tumkur", 
  "Udupi", 
  "Uttara Kannada", 
  "Vijayapura", 
  "Yadgir",

  // Tamil Nadu
  "Chennai", 
  "Coimbatore", 
  "Madurai", 
  "Tiruchirappalli", 
  "Salem", 
  "Tirunelveli", 
  "Erode", 
  "Vellore", 
  "Thoothukudi", 
  "Thanjavur", 
  "Dindigul", 
  "Cuddalore", 
  "Kanchipuram", 
  "Villupuram", 
  "Sivaganga", 
  "Tiruvannamalai", 
  "Dharmapuri", 
  "Namakkal", 
  "Karur", 
  "Pudukkottai", 
  "Ramanathapuram", 
  "Virudhunagar", 
  "Theni", 
  "Krishnagiri", 
  "Tiruvallur", 
  "Kanyakumari", 
  "Nagapattinam", 
  "Tiruvarur", 
  "Nilgiris", 
  "Perambalur", 
  "Ariyalur", 
  "Tiruppur", 
  "Ranipet",

  // Andhra Pradesh & Telangana
  "Hyderabad", 
  "Warangal", 
  "Karimnagar", 
  "Nizamabad", 
  "Adilabad", 
  "Mahbubnagar", 
  "Rangareddy", 
  "Medak", 
  "Nalgonda", 
  "Khammam", 
  "Visakhapatnam", 
  "Vijayawada", 
  "Guntur", 
  "Nellore", 
  "Kurnool", 
  "Kadapa", 
  "Tirupati", 
  "Anantapur", 
  "Chittoor", 
  "East Godavari", 
  "West Godavari", 
  "Krishna", 
  "Prakasam", 
  "Srikakulam", 
  "Vizianagaram", 
  "Ramagundam", 
  "Suryapet", 
  "Miryalaguda", 
  "Jagtial",

  // Kerala
  "Thiruvananthapuram", 
  "Kollam", 
  "Pathanamthitta", 
  "Alappuzha", 
  "Kottayam", 
  "Idukki", 
  "Ernakulam", 
  "Thrissur", 
  "Palakkad", 
  "Malappuram", 
  "Kozhikode", 
  "Wayanad", 
  "Kannur", 
  "Kasaragod", 
  "Kochi",

  // Maharashtra
  "Mumbai", 
  "Pune", 
  "Nagpur", 
  "Thane", 
  "Nashik", 
  "Aurangabad", 
  "Solapur", 
  "Amravati", 
  "Kolhapur", 
  "Sangli", 
  "Akola", 
  "Latur", 
  "Dhule", 
  "Ahmednagar", 
  "Chandrapur", 
  "Jalgaon", 
  "Parbhani", 
  "Jalna", 
  "Bhiwandi", 
  "Nanded", 
  "Satara", 
  "Yavatmal", 
  "Raigad", 
  "Osmanabad", 
  "Nandurbar", 
  "Wardha", 
  "Ratnagiri", 
  "Sindhudurg", 
  "Hingoli", 
  "Washim", 
  "Buldhana", 
  "Gadchiroli", 
  "Beed", 
  "Gondia",

  // Gujarat
  "Ahmedabad", 
  "Surat", 
  "Vadodara", 
  "Rajkot", 
  "Bhavnagar", 
  "Jamnagar", 
  "Gandhinagar", 
  "Anand", 
  "Bharuch", 
  "Mehsana", 
  "Patan", 
  "Sabarkantha", 
  "Surendranagar", 
  "Kheda", 
  "Panchmahals", 
  "Dahod", 
  "Valsad", 
  "Navsari", 
  "Tapi", 
  "Dang", 
  "Porbandar", 
  "Junagadh", 
  "Amreli", 
  "Kachchh", 
  "Banaskantha",

  // Rajasthan
  "Jaipur", 
  "Jodhpur", 
  "Kota", 
  "Bikaner", 
  "Ajmer", 
  "Udaipur", 
  "Bhilwara", 
  "Alwar", 
  "Bharatpur", 
  "Sikar", 
  "Pali", 
  "Nagaur", 
  "Tonk", 
  "Bundi", 
  "Sawai Madhopur", 
  "Jhunjhunu", 
  "Barmer", 
  "Jalore", 
  "Jaisalmer", 
  "Sirohi", 
  "Churu", 
  "Hanumangarh", 
  "Sri Ganganagar", 
  "Karauli", 
  "Rajsamand", 
  "Dungarpur", 
  "Banswara", 
  "Chittorgarh", 
  "Dausa", 
  "Dholpur", 
  "Jhalawar", 
  "Pratapgarh",

  // Other Major Districts
  "Delhi", 
  "Gurgaon", 
  "Faridabad", 
  "Ghaziabad", 
  "Noida", 
  "Lucknow", 
  "Kanpur", 
  "Agra", 
  "Varanasi", 
  "Meerut", 
  "Allahabad", 
  "Bareilly", 
  "Aligarh", 
  "Moradabad", 
  "Kolkata", 
  "Howrah", 
  "Durgapur", 
  "Asansol", 
  "Siliguri", 
  "Bhopal", 
  "Indore", 
  "Gwalior", 
  "Jabalpur", 
  "Ujjain", 
  "Patna", 
  "Gaya", 
  "Bhagalpur", 
  "Muzaffarpur"
].sort(); // Sort alphabetically for easier finding

// Export as grouped object for UI organization (optional)
export const DISTRICTS_BY_STATE = {
  Karnataka: [
    "Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", 
    "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", 
    "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Hassan", 
    "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal", 
    "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", 
    "Tumkur", "Udupi", "Uttara Kannada", "Vijayapura", "Yadgir"
  ],
  "Tamil Nadu": [
    "Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", 
    "Tirunelveli", "Erode", "Vellore", "Thoothukudi", "Thanjavur", 
    "Dindigul", "Cuddalore", "Kanchipuram", "Villupuram", "Sivaganga", 
    "Tiruvannamalai", "Dharmapuri", "Namakkal", "Karur", "Pudukkottai", 
    "Ramanathapuram", "Virudhunagar", "Theni", "Krishnagiri", "Tiruvallur", 
    "Kanyakumari", "Nagapattinam", "Tiruvarur", "Nilgiris", "Perambalur", 
    "Ariyalur", "Tiruppur", "Ranipet"
  ]
};